# Generated by Django 3.2 on 2024-01-10 12:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dbuser',
            name='confirmation_code',
        ),
        migrations.AlterField(
            model_name='dbuser',
            name='bio',
            field=models.TextField(blank=True),
        ),
    ]
