# Generated by Django 3.2 on 2023-12-31 10:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='dbuser',
            name='confirmation_code',
            field=models.CharField(blank=True, max_length=6),
        ),
    ]
