# Generated by Django 3.2 on 2023-12-31 10:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_dbuser_confirmation_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dbuser',
            name='password',
            field=models.CharField(blank=True, max_length=128),
        ),
    ]
