# Generated by Django 3.2 on 2024-01-02 19:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_alter_dbuser_password'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='dbuser',
            managers=[
            ],
        ),
        migrations.AlterField(
            model_name='dbuser',
            name='password',
            field=models.CharField(max_length=128, verbose_name='password'),
        ),
    ]
