# Generated by Django 3.2 on 2023-12-30 15:30

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import users.models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('titles', '0002_comments_reviews'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reviews',
            name='text',
        ),
        migrations.AddField(
            model_name='comments',
            name='author',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='users.dbuser', verbose_name='Автор'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='reviews',
            name='author',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Автор'),
        ),
        migrations.AddField(
            model_name='reviews',
            name='grade',
            field=models.IntegerField(default=1, validators=[django.core.validators.MaxValueValidator(10), django.core.validators.MinValueValidator(1)]),
        ),
        migrations.AddField(
            model_name='titles',
            name='rating',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=3, null=True, verbose_name='Рейтинг произведения'),
        ),
    ]
